<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIRjvig\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIRjvig/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRIRjvig.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRIRjvig\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerRIRjvig\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'RIRjvig',
    'container.build_id' => 'f6e13c5a',
    'container.build_time' => 1578446035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIRjvig');
