<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ivddGM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ivddGM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ivddGM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ivddGM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2ivddGM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2ivddGM',
    'container.build_id' => 'c24d3525',
    'container.build_time' => 1578444684,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ivddGM');
